// RoleMenuChoice.kt
package com.example.mygame.engine_and_helpers

enum class RoleMenuChoice {
    // shared
    LAST_ORDER_STATUS,

    // CHANCELLOR
    GENERAL_REPORT, HIRE_SPY, ORGANIZE_BALL, ORGANIZE_FESTIVAL, ORGANIZE_RELIGIOUS_FESTIVAL, ORGANIZE_HUNT, SEND_MESSAGE, SEND_MESSAGE_DOVE,

    // DEFENCE
    DEFENCE_STATUS, HIRE_RECRUITER,

    // COIN
    ECONOMICS_STATUS, NEED_MONEY, HIRE_TAX_COLLECTOR, CHANGE_TAXES, SELL_GOODS, BUY_GOODS
}
