package com.example.mygame.database.map

enum class MapMenuAction {
    REPORT, LIST_ARMIES, MOVE_ARMY_HERE, MOVE_PLAYER_HERE, IMPROVE_DEFENSE,
    ORGANIZE_BALL, ORGANIZE_HUNT, ORGANIZE_FESTIVAL, ORGANIZE_RELIGIOUS_FESTIVAL,
    LIST_ACTORS, ORGANIZE_REBELLION_HERE, CLOSE
}